CREATE TABLE "web_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "web_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "web_proposal" (
	"id" varchar(66) PRIMARY KEY NOT NULL,
	"chainId" integer NOT NULL,
	"gate" varchar(42) NOT NULL,
	"nonce" text NOT NULL,
	"callTo" varchar(42) NOT NULL,
	"callValue" text NOT NULL,
	"callData" text NOT NULL,
	"action" jsonb NOT NULL,
	"view" jsonb NOT NULL,
	"deadline" integer NOT NULL,
	"agentSig" text,
	"humanSig" text,
	"status" varchar(16) NOT NULL,
	"txHash" varchar(66),
	"error" text,
	"claimedAt" timestamp with time zone,
	"seq" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "web_proposal_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone NOT NULL,
	"decidedAt" timestamp with time zone,
	"originator" varchar(8) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "web_signer_session" (
	"address" varchar(42) PRIMARY KEY NOT NULL,
	"kind" varchar(16) NOT NULL,
	"lastSeenAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "web_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "proposal_status_idx" ON "web_proposal" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "proposal_one_pending_idx" ON "web_proposal" USING btree ("status") WHERE "web_proposal"."status" = 'PENDING_HUMAN';