CREATE TABLE "web_message" (
	"seq" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "web_message_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"role" varchar(16) NOT NULL,
	"text" text NOT NULL,
	"items" jsonb,
	"toolCalls" jsonb,
	"createdAt" timestamp with time zone NOT NULL
);
