// GENERATED by scripts/export-abi.mjs. Do not edit by hand.
import TappyGateAbi from "../abi/TappyGate.json" with { type: "json" };
import MockTokenAbi from "../abi/MockToken.json" with { type: "json" };
import MockSwapAbi from "../abi/MockSwap.json" with { type: "json" };
import MockMerchantAbi from "../abi/MockMerchant.json" with { type: "json" };

export const abis = { TappyGate: TappyGateAbi, MockToken: MockTokenAbi, MockSwap: MockSwapAbi, MockMerchant: MockMerchantAbi } as const;
export { TappyGateAbi };
export { MockTokenAbi };
export { MockSwapAbi };
export { MockMerchantAbi };

export const deployments = {} as const;

export type DeploymentKey = keyof typeof deployments;
